#!/bin/bash

# Parameters:
# config (required)
# autoconf (optional - used by munin-config)

#%# family=manual
#%# capabilities=autoconf

instance_id=${instanceid-""}
aws_credential_file=${credentialfile-""}
aws_region=${region-"ap-northeast-1"}

export AWS_CREDENTIAL_FILE=$aws_credential_file
export AWS_REGION=$aws_region
export JAVA_HOME=/usr/lib/jvm/jre
export AWS_CLOUDWATCH_HOME=/opt/aws/apitools/mon
export AWS_CLOUDWATCH_URL=https://monitoring.${AWS_REGION}.amazonaws.com
export PATH=$PATH:$HOME/bin:$AWS_CLOUDWATCH_HOME/bin

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

if [ "$1" = "config" ]; then
	echo "graph_title EC2 CPUCreditUsage"
	echo 'graph_args --lower-limit 0'
	echo 'graph_vlabel CPUCreditUsage'
	echo 'graph_scale no'
	echo 'graph_category AWS'
	echo 'graph_info This graph shows the EC2 CPUCreditUsage'

	echo "CPUCreditUsage.label $instance_id"
	echo "CPUCreditUsage.draw LINE2"
	echo "CPUCreditUsage.info The average EC2 CPU Credit Usage"
	echo "CPUCreditUsage.min 0"

	exit 0
fi

if [ "$instance_id" = "" ]; then
	exit 0
fi

if [ "$aws_credential_file" = "" ]; then
	exit 0
fi

stats=`/opt/aws/bin/mon-get-stats CPUCreditUsage --namespace "AWS/EC2" --statistics "Average" --unit "Count" --dimensions "InstanceId=$instance_id" | tail -n 1 | awk '{print $3}'`

echo -n "CPUCreditUsage.value "
echo $stats
